name:                my-neural-nets
version:             0.0.0.0
synopsis:            Neural network library in Haskell
description:         Please see the README on GitHub at <https://github.com/Nickske666/my-neural-nets#readme>
category:            Data science
github:              "NickVdB/my-neural-nets/neural"
license:             BSD3
author:              "Nick Van den Broeck"
maintainer:          nick.van.den.broeck@hotmail.com
copyright:           "2018 Nick Van den Broeck"

dependencies:
- aeson
- base >= 4.7 && < 5
- hmatrix >= 0.19
- MonadRandom
- mtl
- random
- random-shuffle
- singletons
- validity >= 0.4.0.4
- vector

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude
  exposed-modules:
  - Import
  - Neural
  - Neural.Core.Shape
  - Neural.Core.LinearAlgebra
  - Neural.Core.LinearAlgebra.Internal
  - Neural.Core.Layer
  - Neural.Core.Network
  - Neural.Core.HyperParams
  - Neural.Core.HyperParams.Internal
  - Neural.Layers
  - Neural.Layers.Convolutional
  - Neural.Layers.FullyConnected
  - Neural.Layers.Reshape
  - Neural.Layers.Sigmoid
  - Neural.Utils.PositiveDouble
  - Neural.Utils.PositiveDouble.Internal
  - Neural.Utils.PositiveInt
  - Neural.Utils.PositiveInt.Internal
  - Neural.Utils.ProperFraction
  - Neural.Utils.ProperFraction.Internal
  - Neural.Utils.Proxy
  - Neural.CreateRandom
  - Neural.ParamOpt
  - Neural.ParamOpt.DataSet
  - Neural.ParamOpt.Train
  - Neural.ParamOpt.Accuracy
