name:                my-neural-nets
version:             0.0.0.0
synopsis:            Neural network library in Haskell
description:         Please see the README on GitHub at <https://github.com/Nickske666/my-neural-nets#readme>
category:            Data science
github:              "NickVdB/my-neural-nets"
license:             BSD3
author:              "Nick Van den Broeck"
maintainer:          nick.van.den.broeck@hotmail.com
copyright:           "2018 Nick Van den Broeck"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- hmatrix >= 0.19
- singletons
- validity >= 0.4.0.4
- vector

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude
  exposed-modules:
  - Import
  - Neural
  - Neural.Shape
  - Neural.LinearAlgebra
  - Neural.LinearAlgebra.Internal
  - Neural.PositiveDouble
  - Neural.PositiveDouble.Internal
  - Neural.ProperFraction
  - Neural.ProperFraction.Internal
  - Neural.HyperParams
  - Neural.HyperParams.Internal

executables:
  my-neural-nets-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-neural-nets

tests:
  my-neural-nets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - genvalidity >= 0.4.0.4
    - genvalidity-hspec >= 0.5
    - QuickCheck >= 2.11
    - my-neural-nets
    other-modules:
    - TestImport
    - TestUtils
    - Neural.Core.Gen
    - Neural.Core.InstanceSpec
    - Neural.LinearAlgebra.Gen
    - Neural.LinearAlgebra.InstanceSpec
    - Neural.Shape.Gen
    - Neural.Shape.InstanceSpec
    - Neural.Utils.Gen
    - Neural.Utils.InstanceSpec
