packages:
- pinky
- pinky-test-utils
- pinky-integration-test
resolver: lts-11.10
nix:
  packages: [blas, liblapack, gfortran.cc.lib]
extra-deps:
- hmatrix-0.19.0.0
- genvalidity-0.5.0.3
- genvalidity-hspec-0.6.0.3
- genvalidity-property-0.2.0.2
- QuickCheck-2.11.1
- validity-0.6.0.0
- base-compat-batteries-0.10.1
- base-compat-0.10.1
- aeson-1.3.1.1
- criterion-1.4.1.0
- git: git@github.com:Nickske666/massiv.git
  commit: ff77314c5a0cba3044da464cbf390e9d6b0dd2d7
  subdirs:
    - massiv
