packages:
- pinky
- pinky-test-utils
- pinky-example
- pinky-test-utils
resolver: lts-11.10
nix:
  packages: [blas, liblapack, gfortran.cc.lib]
extra-deps:
- hmatrix-0.19.0.0
- genvalidity-0.5.0.3
- genvalidity-hspec-0.6.0.3
- genvalidity-property-0.2.0.2
- QuickCheck-2.11.1
- validity-0.6.0.0
- base-compat-batteries-0.10.1
- base-compat-0.10.1
- aeson-1.3.1.1
- criterion-1.4.1.0
- git: git@github.com:Nickske666/massiv.git
  commit: 1b20398766da1c4e8cdb274feffde10de8965ab9
  subdirs:
    - massiv
    - massiv-test-utils
