name:                pinky-integration-test
version:             0.0.0.0
synopsis:            Integration tests for Pinky
description:         Please see the README on GitHub at <https://github.com/Nickske666/pinky#readme>
category:            Data science
license:             BSD3
author:              "Nick Van den Broeck"
maintainer:          nick.van.den.broeck@hotmail.com
copyright:           "2018 Nick Van den Broeck"

dependencies:
- base >= 4.7 && < 5
- bytestring
- hmatrix >= 0.18
- hspec
- genvalidity >= 0.4.0.4
- genvalidity-hspec >= 0.5
- MonadRandom
- mtl
- pinky
- pinky-test-utils
- random
- random-shuffle
- singletons
- validity >= 0.4.0.4
- vector
- megaparsec
- path
- path-io

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude
  exposed-modules:
  - Utils.Files
  - Utils.Parser
  - Utils.Zip
  - MNIST.DataSet
  - MNIST.Parser
  - MNIST.Parser.Internal
  - MNIST.Load
  - NN.Network
  - NN.Params
  other-modules:
  - Import

tests:
  pinky-integration-test:
    main:               Spec
    source-dirs:        test
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pinky-integration-test
    other-modules:
    - TestImport

benchmarks:
  pinky-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts 
    - -with-rtsopts=-N
    - -Wall    
    - -fno-warn-name-shadowing
    dependencies:
    - criterion
    - QuickCheck
    - pinky-integration-test
